### ISSUE TITLE
Question about functionality provided

### ISSUE THREAD

**Issue by YiannisGkoufas** [openshift/assisted-service#2013]
Hi, I am looking at the repo and try to understand about its functionality.
If visit https://cloud.redhat.com/openshift/assisted-installer/clusters and try to create a cluster it generates a discovery-image iso that I can boot a node and get discovered in the dashboard so I can install openshift4.

I currently try to do the same process for ppc64le nodes, so my idea was to use this repo, build the discovery iso for ppc64le and follow the same process in the cloud.redhat.com portal to install openshift4.

Would something like the above be possible, using the current repo?

**Comment by rollandf** [comment]
This is WIP see:
https://github.com/openshift/assisted-service/pull/2305
