### ISSUE TITLE
static IP support

### ISSUE THREAD

**Issue by dsimonov1** [openshift/assisted-service#2492]
Hi

Is this the right place to ask about feature available in version quay.io/ocpmetal/assisted-service:v1.0.16.2, namely support for static IPs? It is missing from the latest version and we desperately need it for a big Telco lab. 

Now using quay.io/ocpmetal/assisted-service:stable.10.08.2021-22.10 and this feature is no longer there.

I am trying to map all the dependencies and versions so was checking the API here: https://generator.swagger.io/?url=https://raw.githubusercontent.com/openshift/assisted-service/master/swagger.yaml

Is above swagger API referring to master branch?

Thanks

**Comment by eranco74** [comment]
We switched to work with NMstate https://github.com/openshift/assisted-service/blob/master/docs/user-guide/restful-api-guide.md#setting-static-network-config

The above swagger is referring to master branch.
