### ISSUE TITLE
version 4.7 pulled from AI? 

### ISSUE THREAD

**Issue by TiloGit** [openshift/assisted-service#2655]
as of today I can see on https://console.redhat.com/openshift/assisted-installer/clusters/~new

- OpenShift 4.6.16
- OpenShift 4.8.9

any reason why 4.7 is not available anymore?

**Comment by romfreiman** [comment]
We decided to provide only the latest version available for now. We still keep 4.6.16 due to specific ask though.

**Comment by TiloGit** [comment]
thanks for the quick reply 

if AI leaves the tech preview phase would all supported OCP versions be available for assistant installer or only certain?
