### ISSUE TITLE
creating storage class for virtualization

### ISSUE THREAD

**Issue by sanjeevshar** [openshift/assisted-service#3015]
For Virtualization workload, I need a Storage Class. How do I create a storage class  that uses local storage on the node. I configured Local Storage operator and it created a single PV for the whole disk. I need a SC that can support multiple PVCs using local storage on the node.

**Comment by romfreiman** [comment]
If it's multiple nodes, assisted supports deployment of ocs as part of the installation process.
For sno, you can use hpp (host path provisioner) for dynamic pvcs.

**Comment by sanjeevshar** [comment]
Thanks! Can you please provide me a pointer to documentation that describes how to create a SC that uses HPP.
I have installed OpenShift 4.8.17  on my SNO.

**Comment by rollandf** [comment]
https://docs.openshift.com/container-platform/4.9/storage/persistent_storage/persistent-storage-hostpath.html

**Comment by rollandf** [comment]
You can also check:
https://github.com/kubevirt/hostpath-provisioner

**Comment by sanjeevshar** [comment]
hostpath-provisioner operator failed to install. Do I need to install anything else before I install hostpath-provisioner.

[core@opti-7090 hostpath]$ oc get po -n hostpath-provisioner
NAME                                             READY   STATUS              RESTARTS   AGE
hostpath-provisioner-operator-77c9dbf667-2bgq6   0/1     ContainerCreating   0          81m
[core@opti-7090 hostpath]$ oc describe  po hostpath-provisioner-operator-77c9dbf667-2bgq6 -n hostpath-provisioner
Name:           hostpath-provisioner-operator-77c9dbf667-2bgq6
Namespace:      hostpath-provisioner
Priority:       0
Node:           opti-7090/192.168.0.116
Start Time:     Tue, 14 Dec 2021 20:44:53 +0000
Labels:         name=hostpath-provisioner-operator
                pod-template-hash=77c9dbf667
                prometheus.hostpathprovisioner.kubevirt.io=true
Annotations:    openshift.io/scc: restricted
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/hostpath-provisioner-operator-77c9dbf667
Containers:
  hostpath-provisioner-operator:
    Container ID:
    Image:         quay.io/kubevirt/hostpath-provisioner-operator:latest
    Image ID:
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      hostpath-provisioner-operator
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   150Mi
    Liveness:   http-get http://:6060/livez delay=30s timeout=1s period=5s #success=1 #failure=1
    Readiness:  http-get http://:6060/readyz delay=5s timeout=1s period=5s #success=1 #failure=1
    Environment:
      WATCH_NAMESPACE:                    hostpath-provisioner (v1:metadata.namespace)
      POD_NAME:                           hostpath-provisioner-operator-77c9dbf667-2bgq6 (v1:metadata.name)
      INSTALLER_PART_OF_LABEL:             (v1:metadata.labels['app.kubernetes.io/part-of'])
      INSTALLER_VERSION_LABEL:             (v1:metadata.labels['app.kubernetes.io/version'])
      OPERATOR_NAME:                      hostpath-provisioner-operator
      OPERATOR_IMAGE:                     quay.io/kubevirt/hostpath-provisioner-operator:latest
      PROVISIONER_IMAGE:                  quay.io/kubevirt/hostpath-provisioner:latest
      CSI_PROVISIONER_IMAGE:              quay.io/kubevirt/hostpath-csi-driver:latest
      NODE_DRIVER_REG_IMAGE:              k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
      LIVENESS_PROBE_IMAGE:               k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
      CSI_SNAPSHOT_IMAGE:                 k8s.gcr.io/sig-storage/csi-snapshotter:v4.2.1
      CSI_SIG_STORAGE_PROVISIONER_IMAGE:  k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1
      VERBOSITY:                          3
      MONITORING_NAMESPACE:
    Mounts:
      /tmp/k8s-webhook-server/serving-certs from apiservice-cert (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7qvt5 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  apiservice-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  hostpath-provisioner-operator-webhook-service-cert
    Optional:    false
  kube-api-access-7qvt5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    81m                   default-scheduler  Successfully assigned hostpath-provisioner/hostpath-provisioner-operator-77c9dbf667-2bgq6 to opti-7090
  Warning  FailedMount  20m (x24 over 79m)    kubelet            Unable to attach or mount volumes: unmounted volumes=[apiservice-cert], unattached volumes=[apiservice-cert kube-api-access-7qvt5]: timed out waiting for the condition
  Warning  FailedMount  6m18s (x45 over 81m)  kubelet            MountVolume.SetUp failed for volume "apiservice-cert" : secret "hostpath-provisioner-operator-webhook-service-cert" not found
  Warning  FailedMount  21s (x6 over 77m)     kubelet            Unable to attach or mount volumes: unmounted volumes=[apiservice-cert], unattached volumes=[kube-api-access-7qvt5 apiservice-cert]: timed out waiting for the condition
[core@opti-7090 hostpath]$
