### ISSUE TITLE
Pods work fine but unable to bring up VMs 

### ISSUE THREAD

**Issue by sanjeevshar** [openshift/assisted-service#3054]
When I try to bring up a VM, I get the following error: server error. 
command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2021-12-14T12:57:02.789388Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-private/vmi-disks/rootdisk/disk.img\",\"node-name\":\"libvirt-1-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: Could not open '/var/run/kubevirt-private/vmi-disks/rootdisk/disk.img': Permission denied')"

Strange thing is that there is no var/run/kubevirt-private/vmi-disks/rootdisk/disk.img file on the node.

I am using NFS based storage to spin up Pods and VM. I have no issues with Pods.

**Comment by dankenigsberg** [comment]
Can you share the yaml of your VirtualMachine? Could it be that you are using a very old containerDisk image, which does not have disk.img readable by the qemu user (107)?
