### ISSUE TITLE
Unable to create cluster with name starting with a number

### ISSUE THREAD

**Issue by charlottemach** [openshift/assisted-service#3202]
Currently [this line](https://github.com/openshift/assisted-service/blob/b51d4bee708a0d2a72a84dc529d83b0cde2fbac0/internal/cluster/validations/validations.go#L32)
```
clusterNameRegex    = "^([a-z]([-a-z0-9]*[a-z0-9])?)*$"
```
limits cluster names to start with a letter, is there an underlying reason for that?

If not, I'd like to add a PR to widen the naming requirements to be able to name clusters starting with a number.

**Comment by rollandf** [comment]
This is base on the OpenShift Installer validation:

https://github.com/openshift/installer/blob/master/pkg/validate/validate.go#L110

**Comment by rollandf** [comment]
Thank you @charlottemach
