### ISSUE TITLE
 Incorrect conversion to Gigabytes 

### ISSUE THREAD

**Issue by nsatsia** [openshift/assisted-service#3620]
```
sizeGB := int(disk.SizeBytes / (1024 * 3))
```
Should be
```
sizeGB := int(disk.SizeBytes / Pow(1024, 3))
```

In the following code:
https://github.com/openshift/assisted-service/blob/29236b32130c6d17c9f8dbabf38b342516f0eb36/internal/controller/controllers/bmh_agent_controller.go#L912

**Comment by mkowalski** [comment]
Thanks for pointing out this issue! It gets fixed by https://github.com/openshift/assisted-service/pull/4205
