### ISSUE TITLE
save-partlabel and save-partindex coreos-installer arguments are not honored because the partition is formatted previously

### ISSUE THREAD

**Issue by alosadagrande** [openshift/assisted-service#3664]
The arguments that can be set to keep a partition of the installation disk are not honored because the installation disk is formated before running the coreos-installer utility [here](https://github.com/openshift/assisted-service/blob/master/internal/host/hostcommands/install_cmd.go#L224) and then a [disk performance test is run](https://github.com/openshift/assisted-service/blob/master/internal/host/hostcommands/disk_performance_cmd.go)

From the assisted service I can see that the arguments are passed properly to the coreos-installer binary: 

```
Apr 13 09:20:07 snonode.virt01.eko4.cloud.lab.eng.bos.redhat.com installer[8571]: time="2022-04-13T09:20:07Z" level=info msg="Writing image and ignition to disk with arguments: [install --insecure -i /opt/openshift/master.ign --image-url 
http://10.19.140.20/rhcos-4.10.3-x86_64-metal.x86_64.raw.gz --save-partlabel data --append-karg ip=ens3:dhcp /dev/vda]"
```

but the partition is not saved to /dev/vda5 as expected:

```
[root@snonode ~]# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0  15.7G  0 loop /run/ephemeral
loop1    7:1    0 882.7M  0 loop /sysroot
sr0     11:0    1   102M  0 rom  
vda    252:0    0   120G  0 disk 
├─vda1 252:1    0     1M  0 part 
├─vda2 252:2    0   127M  0 part 
├─vda3 252:3    0   384M  0 part 
└─vda4 252:4    0   3.3G  0 part 
```

It just works if I run the coreos-installer + args in the command line.  The device format I think it is also that the coreos-installer does by checking the help flag:

```
        --preserve-on-error         
            Don't clear partition table on error
            
            If installation fails, coreos-installer normally clears the destination's partition table to prevent booting from invalid boot media.  Skip clearing the partition table as a
            debugging aid.
```

**Comment by mkowalski** [comment]
Hi, we are currently working on a few stories related to the partition tables. Please ping us via internal slack if this is still an issue
