### ISSUE TITLE
OKD install fails using podman

### ISSUE THREAD

**Issue by loganmc10** [openshift/assisted-service#3976]
Using the latest podman image to try and deploy OKD. I tried using a fake pull secret (```{"auths":{"fake":{"auth":"aWQ6cGFzcwo="}}}```) and my pull secret from Red Hat, same result.

![image](https://user-images.githubusercontent.com/848146/174514604-94acb84b-6146-4a5b-915f-4fad231e2f4d.png)

Here is the user.ign file (I think this is the ignition file it is complaining about?):
![image](https://user-images.githubusercontent.com/848146/174515106-6bacb5af-9681-4fe3-a362-b057380f83b8.png)

**Comment by loganmc10** [comment]
Maybe related to https://github.com/openshift/assisted-service/pull/3951

**Comment by avishayt** [comment]
I'm guessing that this is because the ISO doesn't have multipathd installed? Please verify.

**Comment by pdfruth** [comment]
@avishayt 
No, I'm suggesting the problem is to do with the [internal/ignition/ignition.go](https://github.com/openshift/assisted-service/blob/73fd2631a5c4fc60cca8b71548ac272e0801d650/internal/ignition/ignition.go) code.
It is generating an ignition file that has invalid json. since the change in this [commit](https://github.com/avishayt/assisted-service/commit/59afc112e00af66f553988da033849524f35e1a8)

As I suggested in my earlier [comment](https://github.com/openshift/assisted-service/issues/3976#issuecomment-1164987064), shouldn't there be a contents element containing the service definition for the **multipathd.service**

**Comment by avishayt** [comment]
This is strange because in OpenShift/RHCOS, it is working.  I SSH into an agent and see:

```
[core@localhost ~]$ systemctl status multipathd
● multipathd.service - Device-Mapper Multipath Device Controller
   Loaded: loaded (/usr/lib/systemd/system/multipathd.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2022-06-26 09:14:33 UTC; 3min 20s ago
  Process: 1228 ExecStartPre=/sbin/multipath -A (code=exited, status=0/SUCCESS)
  Process: 1226 ExecStartPre=/sbin/modprobe -a scsi_dh_alua scsi_dh_emc scsi_dh_rdac dm-multipath (code=exited, status=0/SUCCESS)
 Main PID: 1230 (multipathd)
   Status: "up"
    Tasks: 7
   Memory: 15.9M
   CGroup: /system.slice/multipathd.service
           └─1230 /sbin/multipathd -d -s

Jun 26 09:14:33 localhost systemd[1]: Starting Device-Mapper Multipath Device Controller...
Jun 26 09:14:33 localhost multipathd[1230]: --------start up--------
Jun 26 09:14:33 localhost multipathd[1230]: read /etc/multipath.conf
Jun 26 09:14:33 localhost multipathd[1230]: path checkers start up
Jun 26 09:14:33 localhost systemd[1]: Started Device-Mapper Multipath Device Controller.
```

```
[core@localhost ~]$ cat /etc/systemd/system/sysinit.target.wants/multipathd.service
[Unit]
Description=Device-Mapper Multipath Device Controller
Wants=systemd-udev-trigger.service systemd-udev-settle.service
Before=iscsi.service iscsid.service lvm2-activation-early.service
Before=local-fs-pre.target blk-availability.service shutdown.target
After=multipathd.socket systemd-udev-trigger.service systemd-udev-settle.service
ConditionPathExists=/etc/multipath.conf
DefaultDependencies=no
Conflicts=shutdown.target
ConditionKernelCommandLine=!nompath
ConditionKernelCommandLine=!multipath=off

[Service]
Type=notify
NotifyAccess=main
LimitCORE=infinity
ExecStartPre=-/sbin/modprobe -a scsi_dh_alua scsi_dh_emc scsi_dh_rdac dm-multipath
ExecStartPre=-/sbin/multipath -A
ExecStart=/sbin/multipathd -d -s
ExecReload=/sbin/multipathd reconfigure
TasksMax=infinity

[Install]
WantedBy=sysinit.target
Also=multipathd.socket
```

**Comment by vrutkovs** [comment]
FCOS doesn't have `multipath.service` pre-installed, but imo its an Ignition bug - it should not crash on enabling the service which doesn't exist, or at least give a better error message.

Seems we need to remove multipathd ignition part on OKD deployments (iirc it is being enabled with a flag)

**Comment by avishayt** [comment]
That's what I suspected, thanks for verifying @vrutkovs .  I'll add multipath to the ignition only if not OKD.
