### ISSUE TITLE
SNO disconnted environment openshift cluster installer failed with assisted-service in failed state and its pod showing in degraded state

### ISSUE THREAD

**Issue by poojagupta1418** [openshift/assisted-service#4096]
Installling a single node openshift cluster via crucible playbook , while running assisted-installer on prem job , it is getting failed with assisted service pod in degraded state and assisted-service pod in degraded state.

podman pod ps
POD ID        NAME              STATUS    CREATED       INFRA ID      # OF CONTAINERS
20daebe9ee8d  assisted-service  Degraded  28 hours ago  8b34257730b0  4
b142bdaae025  http_store_pod    Running   30 hours ago  23905c0c0d9d  2

**Comment by mkowalski** [comment]
Hi, this looks more like an issue with https://github.com/redhat-partner-solutions/crucible rather than assisted service
