### ISSUE TITLE
assisted-service is in degraded state due to its container (installer) in exit state.

### ISSUE THREAD

**Issue by poojagupta1418** [openshift/assisted-service#4183]
running crucible playbook for installation of openshift cluster 4.10.18 with rhel 8,4 . After running playbook "deploy_assisted_installer_onprem.yml" , all assisted-service conatiner is created but installer pod in stopped state due to that assisted-service is showing in degraded state.

podman pod ps
POD ID        NAME              STATUS    CREATED       INFRA ID      # OF CONTAINERS
d8550189ca2b  assisted-service  Degraded  20 hours ago  6ac2b790faf3  4
b28d83ab59e5  http_store_pod    Running   2 days ago    43bd63e63a86  2

podman ps -a
CONTAINER ID  IMAGE                                                                COMMAND               CREATED       STATUS                   PORTS                                                                   NAMES
c3d33f14e48c  docker.io/library/registry:latest                                    /etc/docker/regis...  3 weeks ago   Up 2 days ago            0.0.0.0:5002->5000/tcp                                                  Mirror-Registry2
43bd63e63a86  registry-quay.sno.localdomain:5002/ubi8/pause:latest                                       2 days ago    Up 2 days ago            0.0.0.0:80->8080/tcp                                                    b28d83ab59e5-infra
fc718330670e  registry.centos.org/centos/httpd-24-centos7:latest                   /usr/bin/run-http...  2 days ago    Up 2 days ago            0.0.0.0:80->8080/tcp                                                    http_store
6ac2b790faf3  registry-quay.sno.localdomain:5002/ubi8/pause:latest                                       20 hours ago  Up 20 hours ago          0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp  d8550189ca2b-infra
3c3b07228209  registry-quay.sno.localdomain:5002/ocpmetal/postgresql-12:v1.1       run-postgresql        20 hours ago  Up 20 hours ago          0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp  db
5737d15f4f11  registry-quay.sno.localdomain:5002/ocpmetal/ocp-metal-ui:latest      /opt/bitnami/scri...  20 hours ago  Up 20 hours ago          0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp  gui
5613b17ed014  registry-quay.sno.localdomain:5002/ocpmetal/assisted-service:latest  /assisted-service     20 hours ago  Exited (1) 20 hours ago  0.0.0.0:8000->8000/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp  installer

after looking into the logs of stopped container we got below error message:

time="2022-07-25T09:27:40Z" level=info msg="Setting log format: text" func=main.InitLogs file="/go/src/github.com/openshift/origin/cmd/main.go:159"
time="2022-07-25T09:27:40Z" level=info msg="Setting Log Level: info" func=main.InitLogs file="/go/src/github.com/openshift/origin/cmd/main.go:165"
time="2022-07-25T09:27:40Z" level=info msg="Starting bm service" func=main.main file="/go/src/github.com/openshift/origin/cmd/main.go:203"
time="2022-07-25T09:27:40Z" level=fatal msg="Failed to parse OS_IMAGES json \"http://<Bastion nde IP>/discovery/rhcos-4.10.3-x86_64-live.x86_64.iso\"" func=main.main.func1 file="/go/src/github.com/openshift/origin/cmd/main.go:196" error="json: cannot unmarshal string into Go value of type models.OsImages"

observation:
Checked template file used during deployment having same osimages parameter:

POSTGRESQL_DATABASE=installer
POSTGRESQL_PASSWORD=admin
POSTGRESQL_USER=admin
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=admin
DB_PASS=admin
DB_NAME=installer
IMAGE_SERVICE_BASE_URL=http://{{ host | default("ansible_fqdn") }}:8090
#SERVICE_BASE_URL=http://{{ host | default("ansible_fqdn") }}:8090
DEPLOY_TARGET=onprem
STORAGE=filesystem
DUMMY_IGNITION=false
#OS_IMAGES={{ assisted_service_openshift_versions }}
OS_IMAGES="{{ assisted_service_openshift_versions[openshift_version]['rhcos_image'] }}"
OPENSHIFT_VERSIONS={{ assisted_service_openshift_versions | to_json }}
ENABLE_SINGLE_NODE_DNSMASQ=true
PUBLIC_CONTAINER_REGISTRIES=quay.io
NTP_DEFAULT_SERVER=
IPV6_SUPPORT=true
AUTH_TYPE=none

SKIP_CERT_VERIFICATION=true

SELF_VERSION={{ assisted_service_image }}
INSTALLER_IMAGE={{ assisted_installer_image }}
CONTROLLER_IMAGE={{ assisted_installer_controller_image }}
AGENT_DOCKER_IMAGE={{ assisted_installer_agent_image }}

HW_VALIDATOR_MIN_DISK_SIZE_GIB=20

# Format has changed and likely will continue to change for HW validation (Link: https://github.com/openshift/assisted-service/blob/master/onprem-environment#L19)
HW_VALIDATOR_REQUIREMENTS={{ assisted_installer_hardware_validation | to_json }}

Kindly suggest the solution on the same

**Comment by poojagupta1418** [comment]
Hi,

After changing parameter type assisted installer pod is come up with running state but still giving error message :
time="2022-07-27T12:29:37Z" level=error msg="Failed to registered cluster nec with id 0661e00c-1221-433e-8bdd-33c28966ee71" func="github.com/openshift/assisted-service/internal/bminventory.(*bareMetalInventory).RegisterClusterInternal.func1" file="/go/src/github.com/openshift/origin/internal/bminventory/inventory.go:496" cluster_id=0661e00c-1221-433e-8bdd-33c28966ee71 error="Openshift version 4.10 for CPU architecture x86_64 is not supported: The requested CPU architecture (x86_64) isn't specified in release images list" go-id=6295 pkg=Inventory request_id=290aa1e5-d0eb-4e6c-a1aa-b82439305971

Due to this not able to access assisted installer GUI page.

**Comment by mkowalski** [comment]
Hi, this looks more like an issue with https://github.com/redhat-partner-solutions/crucible rather than assisted service
