### ISSUE TITLE
Documentation lacking  for airgapped envs

### ISSUE THREAD

**Issue by djccarew** [openshift/assisted-service#4254]
I am attempting to install OCP 4.10 .20i n an air gapped bm env  using the standalone podman deployment instructions.  I've successfully mirrored the OpenShift install images to my airgapped env as well as the AssistedI Installer images for running in podman.  

The Makefile has the following which implies I will have to rebuild the image to add mirror registry support. 
MIRROR_REG_CA_FILE = mirror_ca.crt.
REGISTRIES_FILE_PATH = registries.conf
MIRROR_REGISTRY_SUPPORT := $(or ${MIRROR_REGISTRY_SUPPORT},False)

 I have  some questions:

1) What is the format of  the registries.conf file referred to above? 

2) What modifications do I have to make to the configmap.yml file that I use to run the AI in podman . In particular what should these values be set to?  RELEASE_IMAGES ,  PUBLIC_CONTAINER_REGISTRIES

3) Do I have to patch  the  install-config file via the AI API to add something like this ?

imageContentSources:
- mirrors:
  - ocp-utilities:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - ocp-utilities:8443/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev

4)  Can I use a local mirror registry in insecure mode (ie skip SSL verification) ?

**Comment by mkowalski** [comment]
Hi,

Question 1 is answered with a sample in https://github.com/openshift/assisted-service/blob/master/docs/user-guide/cloud-with-mirror.md#create-discovery-ignition-patch-file
