### ISSUE TITLE
"Copy to clipboard" button doesn't work after cluster installation

### ISSUE THREAD

**Issue by djian01** [openshift/assisted-service#5997]
After the cluster installation, the "Copy to clipboard" button didn't work. No Password was copied. Although the cluster was up.

![image](https://github.com/openshift/assisted-service/assets/133287587/d7f19e6e-8874-420d-9e8a-1ab78dabe457)

**Comment by mzukal** [comment]
/remove-lifecycle stale
I experienced the same problem. The password could not be copied after a fresh cluster installation.
Luckily, I was able to get the password from HTTP communication.

**Comment by rccrdpccl** [comment]
It would be best to file the issue in the UI component for assisted-service: https://github.com/openshift-assisted/assisted-installer-ui
/cc @ammont82

**Comment by ammont82** [comment]
We have an issue opened about that: https://issues.redhat.com/browse/MGMT-14465

**Comment by rccrdpccl** [comment]
I'll close this issue, we can track it through JIRA
