### ISSUE TITLE
UnAuthenticated Registry Deprecation: registry.svc.ci.openshift.org

### ISSUE THREAD

**Issue by ArthurVardevanyan** [openshift/assisted-service#6552]
registry.svc.ci.openshift.org has been moved to registry.ci.openshift.org:

REF:
- https://bugzilla.redhat.com/show_bug.cgi?id=1951571
- https://bugzilla.redhat.com/show_bug.cgi?id=1951572

PR: https://github.com/openshift/assisted-service/pull/6553

**Comment by ArthurVardevanyan** [comment]
Build Contains PR with update, but still logs same issue:
https://amd64.origin.releases.ci.openshift.org/releasestream/4.17.0-0.okd-scos/release/4.17.0-0.okd-scos-2024-07-15-192426

```error="pull secret for new cluster is invalid: pull secret must contain auth for \"registry.ci.openshift.org\"```

**Comment by danmanor** [comment]
@ArthurVardevanyan thank you, can you please provide more details on how did you got this log? what actions have you taken ?

**Comment by ArthurVardevanyan** [comment]
Same log before change.

This comes from installing the CI builds of OKD via agent based installer.

The stable builds pull from quay.io without issue.

Configs: https://github.com/ArthurVardevanyan/HomeLab/tree/main/sandbox/kubevirt/okd/configs

**Comment by titou10titou10** [comment]
This seems to address the problem described here for OKD/SCOS/UPI/ABI install: https://github.com/okd-project/okd/discussions/1964 

    Failed to register cluster with assisted-service: AssistedServiceError Code: 400 Href:  ID: 400 Kind: Error Reason: pull secret for new cluster is invalid: pull secret must contain auth for \"registry.ci.openshift.org\""

But it does not...
I tried to install`registry.ci.openshift.org/origin/release-scos:4.17.0-0.okd-scos-2024-07-16-072426`that includes #6552/#6553 and it fails the exact same way

You have all the installation details with agent/install config files and logs etc in https://github.com/okd-project/okd/discussions/1964

**Comment by danmanor** [comment]
Thank, I will look into it

**Comment by danmanor** [comment]
commented here - https://github.com/okd-project/okd/discussions/1964

**Comment by ArthurVardevanyan** [comment]
https://github.com/openshift/assisted-service/pull/6642
